server:
  port: 8044

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${INITIAL_DB}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jwt:
    secret: ${JWT_SECRET}
  jpa:
    defer-datasource-initialization: true

    open-in-view: false
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul
          show_sql: true
          format_sql: true
        hbm2ddl.auto: ${SPRING_DATASOURCE_DDL_AUTO}
        #ddl-auto: create-drop
    repositories:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: trace